
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                git branch: 'pipeline_1', url: 'https://github.com/harshit0015/Practice_Pipeline_Project.git'
            }
        }
    }
}
